

        [font]
        size = 13.0

        [font.bold]
        family = "CaskaydiaCove Nerd Font"
        style = "Bold"

        [font.bold_italic]
        family = "CaskaydiaCove Nerd Font"
        style = "Bold Italic"

        [font.italic]
        family = "CaskaydiaCove Nerd Font"
        style = "Italic"

        [font.normal]
        family = "CaskaydiaCove Nerd Font"
        style = "Regular"


[terminal]

[terminal.shell]
program = "/bin/zsh"
args = ["-1"]


[colors.primary]
background = '#121212'
foreground = '#f5f5f5'

[colors.cursor]
cursor = '#C53030'
text = '#121212'

[colors.normal]
black = '#121212'
red = '#B14242'
green = '#D87C4A'
yellow = '#E49A44'
blue = '#4A8B8B'
magenta = '#a7a7a7'
cyan = '#b4b4b4'
white = '#d5d5d5'

[colors.bright]
black = '#949494'
red = '#B14242'
green = '#D87C4A'
yellow = '#E49A44'
blue = '#4A8B8B'
magenta = '#a7a7a7'
cyan = '#b4b4b4'
white = '#d5d5d5'
